### PR TITLE
Add ESP32 GENERIC build

### PR DESCRIPTION
**Pull request by GanerCodes**

### CODE REVIEW

**Comment by GanerCodes** [comment]
ok I suck at github apparently but this pull request should include adding `generic.sh` to the esp32 build scripts which calls `build_esp32 "ESP32_GENERIC"`

**Comment by v923z** [comment]
@GanerCodes I've re-named generic in the latest commit, so this is going to fail. What do you want to compile for?

**Comment by GanerCodes** [comment]
ESP32_GENERIC is the one I'm trying to compile for, I ran it in a docker container and it worked
https://gist.github.com/sekcompsci/2bf39e715d5fe47579fa184fa819f421

**Comment by v923z** [comment]
> ESP32_GENERIC is the one I'm trying to compile for, I ran it in a docker container and it worked https://gist.github.com/sekcompsci/2bf39e715d5fe47579fa184fa819f421

This is OK, but please, fix the copyright at the top.

**Comment by v923z** [comment]
You've got to set `generic.h` to be executable. 

```bash
chmod a+x generic.h
```

**Comment by v923z** [comment]
Merged. Thanks for contributing!

**Pull request merged**
